### ISSUE TITLE
Contributors with uncapitalized last names

### ISSUE THREAD

**Issue by tbl73** [VictorianResearchWeb/TheCurranIndex#30] opened 2017-09-05 15:27 UTC
Contributors whose last names aren't capitalized (i.e. de Niroy) fall to the end of the alphabetical list of contributors (due to the way Rails alphabetizes).  Need to determine how they should be properly handled.

**Comment by saracarl** [comment] 2018-04-16 10:51
Closing as a dupe of #46

**Closed by saracarl** 2018-04-16 10:51 UTC
